  name: GatorGrader

  on:
    push:
      branches: [ main ]

  env:
    GWIZ_TOKEN: ${{ secrets.GWIZ_TOKEN }}

  jobs:
    grade:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
        with: 
          fetch-depth: '0'
      - name: Setup Python
        if: always()
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Set up grading environment
        run: |
          pip install --upgrade pip
          pip install pipenv
          pipenv install --dev --three
          pip install bs4
          pip install requests
      - name: Grade repository
        run: |
          export PAGES_URL=$(curl -sb -H "Accept:application/json" -u dluman:$GWIZ_TOKEN $GITHUB_API_URL/repos/$GITHUB_REPOSITORY/pages)
          python config/.w3c.py style/recipe-style.css
          gradle grade
        if: always()
        env:   
         PIPENV_VENV_IN_PROJECT: 1
         PIPENV_IGNORE_VIRTUALENVS: 1

